server:
  port: 8765

spring:
  application:
    name: api-gateway-service
#  cloud:
#    gateway:
#      routes:
#        - id: contacts_route
#          uri: "lb://contacts-service"
#          predicates:
#            - Path= /api/v1/contacts/**
#        - id: users_route
#          uri: "lb://user-profile-service"
#          predicates:
#            - Path= /api/v1/users/**

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/