server:
  port: 9001
spring:
  application:
    name: user-profile-service
  datasource:
    url: jdbc:mysql://localhost:3306/regd_users_db?createDatabaseIfNotExist=true
    username: root
    password: 12bantoo
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
#springdoc:
#  swagger-ui:
#    path: /swagger-ui-custom.html

#  http://localhost:9000/v2/api-docs
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


#    14:48:25	Could not connect, server may not be running.	Unable to connect to localhost
#https://studyopedia:com/errors-resolved/fix-cant-connect-to-mysql-server/:

logging:
  level:
    in:
      stackroute:
        userprofile: DEBUG

  file:
    name: userprofileservice.log
#  pattern:
#    file: "%d %level %m\n"
#    console: "%d %level %m\n"